using namespace std;

string gethandle1A() {
    int y = rand() % (101) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "abandoned";};
    if (y==2) {handle1 = "abased";};
    if (y==3) {handle1 = "aberrant";};
    if (y==4) {handle1 = "abels";};
    if (y==5) {handle1 = "abhorrent";};
    if (y==6) {handle1 = "abject";};
    if (y==7) {handle1 = "able";};
    if (y==8) {handle1 = "abomination";};
    if (y==9) {handle1 = "abscission";};
    if (y==10) {handle1 = "absconding";};
    if (y==11) {handle1 = "absolute";};
    if (y==12) {handle1 = "abstruse";};
    if (y==13) {handle1 = "abyss";};
    if (y==14) {handle1 = "abyssal";};
    if (y==15) {handle1 = "acapella";};
    if (y==16) {handle1 = "ace";};
    if (y==17) {handle1 = "acidic";};
    if (y==18) {handle1 = "aconite";};
    if (y==19) {handle1 = "acrimonious";};
    if (y==20) {handle1 = "acryptic";};
    if (y==21) {handle1 = "adamantite";};
    if (y==22) {handle1 = "adios";};
    if (y==23) {handle1 = "adventurous";};
    if (y==24) {handle1 = "aerialist";};
    if (y==25) {handle1 = "aero";};
    if (y==26) {handle1 = "aesthetic";};
    if (y==27) {handle1 = "affable";};
    if (y==28) {handle1 = "afforementioned";};
    if (y==29) {handle1 = "aggressive";};
    if (y==30) {handle1 = "aggro";};
    if (y==31) {handle1 = "agile";};
    if (y==32) {handle1 = "agnogenic";};
    if (y==33) {handle1 = "alchemical";};
    if (y==34) {handle1 = "aleatory";};
    if (y==35) {handle1 = "aleph";};
    if (y==36) {handle1 = "algebraic";};
    if (y==37) {handle1 = "alien";};
    if (y==38) {handle1 = "alleged";};
    if (y==39) {handle1 = "allodic";};
    if (y==40) {handle1 = "allogeneous";};
    if (y==41) {handle1 = "aloof";};
    if (y==42) {handle1 = "allogeneous";};
    if (y==43) {handle1 = "aloof";};
    if (y==44) {handle1 = "alpacas";};
    if (y==45) {handle1 = "alpha";};
    if (y==46) {handle1 = "already";};
    if (y==47) {handle1 = "ambrosine";};
    if (y==48) {handle1 = "analog";};
    if (y==49) {handle1 = "ancient";};
    if (y==50) {handle1 = "anelie";};
    if (y==51) {handle1 = "angelic";};
    if (y==52) {handle1 = "angular";};
    if (y==53) {handle1 = "animalistic";};
    if (y==54) {handle1 = "animated";};
    if (y==55) {handle1 = "animatronic";};
    if (y==56) {handle1 = "annoying";};
    if (y==57) {handle1 = "anonymous";};
    if (y==58) {handle1 = "antagonized";};
    if (y==59) {handle1 = "ante";};
    if (y==60) {handle1 = "anti";};
    if (y==61) {handle1 = "antipasto";};
    if (y==62) {handle1 = "antisocial";};
    if (y==63) {handle1 = "antic";};
    if (y==64) {handle1 = "apathetic";};
    if (y==65) {handle1 = "apocalypse";};
    if (y==66) {handle1 = "apostolic";};
    if (y==67) {handle1 = "appolos";};
    if (y==68) {handle1 = "apprehensive";};
    if (y==69) {handle1 = "appropriate";};
    if (y==70) {handle1 = "aqua";};
    if (y==71) {handle1 = "aquatic";};
    if (y==72) {handle1 = "arachnes";};
    if (y==73) {handle1 = "arachnids";};
    if (y==74) {handle1 = "arcane";};
    if (y==75) {handle1 = "arch";};
    if (y==76) {handle1 = "archaic";};
    if (y==77) {handle1 = "archimedes";};
    if (y==78) {handle1 = "archival";};
    if (y==79) {handle1 = "arctic";};
    if (y==80) {handle1 = "arduous";};
    if (y==81) {handle1 = "arid";};
    if (y==82) {handle1 = "aristocratic";};
    if (y==83) {handle1 = "artifactual";};
    if (y==84) {handle1 = "arsenic";};
    if (y==85) {handle1 = "artificial";};
    if (y==86) {handle1 = "artistic";};
    if (y==87) {handle1 = "asbestos";};
    if (y==88) {handle1 = "ascended";};
    if (y==89) {handle1 = "ascetic";};
    if (y==90) {handle1 = "ashen";};
    if (y==91) {handle1 = "athanasy";};
    if (y==92) {handle1 = "atomic";};
    if (y==93) {handle1 = "attuned";};
    if (y==94) {handle1 = "atypical";};
    if (y==95) {handle1 = "authorized";};
    if (y==96) {handle1 = "auto";};
    if (y==97) {handle1 = "automated";};
    if (y==98) {handle1 = "avid";};
    if (y==99) {handle1 = "awkward";};
    if (y==100) {handle1 = "azerothian";};
    if (y==101) {handle1 = "azure";};
    return handle1;
}

string gethandle1B() {
    int y = rand() % (52) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "backfire";};
    if (y==2) {handle1 = "backup";};
    if (y==3) {handle1 = "balanced";};
    if (y==4) {handle1 = "baldrs";};
    if (y==5) {handle1 = "baleful";};
    if (y==6) {handle1 = "ballistic";};
    if (y==7) {handle1 = "bandwagon";};
    if (y==8) {handle1 = "barenecked";};
    if (y==9) {handle1 = "baritone";};
    if (y==10) {handle1 = "barmy";};
    if (y==11) {handle1 = "baseball";};
    if (y==12) {handle1 = "basic";};
    if (y==13) {handle1 = "batter";};
    if (y==14) {handle1 = "beautiful";};
    if (y==15) {handle1 = "beethovens";};
    if (y==16) {handle1 = "belphegors";};
    if (y==17) {handle1 = "benedicts";};
    if (y==18) {handle1 = "benevolent";};
    if (y==19) {handle1 = "benign";};
    if (y==20) {handle1 = "beta";};
    if (y==21) {handle1 = "bigoted";};
    if (y==22) {handle1 = "binary";};
    if (y==23) {handle1 = "bio";};
    if (y==24) {handle1 = "birding";};
    if (y==25) {handle1 = "bisquick";};
    if (y==26) {handle1 = "bitter";};
    if (y==27) {handle1 = "bittersweet";};
    if (y==28) {handle1 = "blackout";};
    if (y==29) {handle1 = "blade";};
    if (y==30) {handle1 = "blasted";};
    if (y==31) {handle1 = "blatant";};
    if (y==32) {handle1 = "blaze";};
    if (y==33) {handle1 = "bleeding";};
    if (y==34) {handle1 = "blended";};
    if (y==35) {handle1 = "blind";};
    if (y==36) {handle1 = "blood";};
    if (y==37) {handle1 = "bloody";};
    if (y==38) {handle1 = "boastful";};
    if (y==39) {handle1 = "boggart";};
    if (y==40) {handle1 = "bolide";};
    if (y==41) {handle1 = "bomb";};
    if (y==42) {handle1 = "bonsai";};
    if (y==43) {handle1 = "book";};
    if (y==44) {handle1 = "botanical";};
    if (y==45) {handle1 = "brackish";};
    if (y==46) {handle1 = "bramble";};
    if (y==47) {handle1 = "broken";};
    if (y==48) {handle1 = "buffalo";};
    if (y==49) {handle1 = "bumbling";};
    if (y==50) {handle1 = "buriedin";};
    if (y==51) {handle1 = "burnt";};
    if (y==52) {handle1 = "byzantine";};
    return handle1;
}

string gethandle1C() {
    int y = rand() % (105) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "cacheted";};
    if (y==2) {handle1 = "calamitous";};
    if (y==3) {handle1 = "calcium";};
    if (y==4) {handle1 = "calico";};
    if (y==5) {handle1 = "caliginous";};
    if (y==6) {handle1 = "caligulas";};
    if (y==7) {handle1 = "calm";};
    if (y==8) {handle1 = "cambions";};
    if (y==9) {handle1 = "cambrian";};
    if (y==10) {handle1 = "campbell";};
    if (y==11) {handle1 = "cancerous";};
    if (y==12) {handle1 = "candid";};
    if (y==13) {handle1 = "candy";};
    if (y==14) {handle1 = "canis";};
    if (y==15) {handle1 = "cannon";};
    if (y==16) {handle1 = "canon";};
    if (y==17) {handle1 = "cantankerous";};
    if (y==18) {handle1 = "capricious";};
    if (y==19) {handle1 = "capriciously";};
    if (y==20) {handle1 = "caprine";};
    if (y==21) {handle1 = "captious";};
    if (y==22) {handle1 = "carapace";};
    if (y==23) {handle1 = "carcino";};
    if (y==24) {handle1 = "cardinal";};
    if (y==25) {handle1 = "career";};
    if (y==26) {handle1 = "careworn";};
    if (y==27) {handle1 = "cascading";};
    if (y==28) {handle1 = "caste";};
    if (y==29) {handle1 = "castellar";};
    if (y==30) {handle1 = "casual";};
    if (y==31) {handle1 = "casually";};
    if (y==32) {handle1 = "cataclysmic";};
    if (y==33) {handle1 = "catastrophically";};
    if (y==34) {handle1 = "catnip";};
    if (y==35) {handle1 = "caustic";};
    if (y==36) {handle1 = "cautious";};
    if (y==37) {handle1 = "cell";};
    if (y==38) {handle1 = "cello";};
    if (y==39) {handle1 = "centaurs";};
    if (y==40) {handle1 = "cerise";};
    if (y==41) {handle1 = "challenge";};
    if (y==42) {handle1 = "chaos";};
    if (y==43) {handle1 = "chaotic";};
    if (y==44) {handle1 = "charmed";};
    if (y==45) {handle1 = "charming";};
    if (y==46) {handle1 = "chemical";};
    if (y==47) {handle1 = "cherry";};
    if (y==48) {handle1 = "cherubic";};
    if (y==49) {handle1 = "cheshire";};
    if (y==50) {handle1 = "chicane";};
    if (y==51) {handle1 = "childish";};
    if (y==52) {handle1 = "chimerical";};
    if (y==53) {handle1 = "chirons";};
    if (y==54) {handle1 = "cinder";};
    if (y==55) {handle1 = "cinnabar";};
    if (y==56) {handle1 = "circuitous";};
    if (y==57) {handle1 = "classless";};
    if (y==58) {handle1 = "classy";};
    if (y==59) {handle1 = "cleft";};
    if (y==60) {handle1 = "clenched";};
    if (y==61) {handle1 = "clever";};
    if (y==62) {handle1 = "clockwork";};
    if (y==63) {handle1 = "cloistered";};
    if (y==64) {handle1 = "cloven";};
    if (y==65) {handle1 = "clownfish";};
    if (y==66) {handle1 = "coaxial";};
    if (y==67) {handle1 = "coffeehouse";};
    if (y==68) {handle1 = "cold";};
    if (y==69) {handle1 = "collected";};
    if (y==70) {handle1 = "colorful";};
    if (y==71) {handle1 = "comatose";};
    if (y==72) {handle1 = "computational";};
    if (y==73) {handle1 = "concave";};
    if (y==74) {handle1 = "concerned";};
    if (y==75) {handle1 = "condescending";};
    if (y==76) {handle1 = "confused";};
    if (y==77) {handle1 = "consequential";};
    if (y==78) {handle1 = "conservative";};
    if (y==79) {handle1 = "consuming";};
    if (y==80) {handle1 = "cool";};
    if (y==81) {handle1 = "cord";};
    if (y==82) {handle1 = "chord";};
    if (y==83) {handle1 = "corrupted";};
    if (y==84) {handle1 = "cosmic";};
    if (y==85) {handle1 = "cotidal";};
    if (y==86) {handle1 = "counter";};
    if (y==87) {handle1 = "crabapple";};
    if (y==88) {handle1 = "crabby";};
    if (y==89) {handle1 = "crab";};
    if (y==90) {handle1 = "crackerbarrel";};
    if (y==91) {handle1 = "crackerjack";};
    if (y==92) {handle1 = "crafty";};
    if (y==93) {handle1 = "craft";};
    if (y==94) {handle1 = "cratering";};
    if (y==95) {handle1 = "crawdad";};
    if (y==96) {handle1 = "cray";};
    if (y==97) {handle1 = "crazy";};
    if (y==98) {handle1 = "cremated";};
    if (y==99) {handle1 = "creepy";};
    if (y==100) {handle1 = "critical";};
    if (y==101) {handle1 = "crude";};
    if (y==102) {handle1 = "cryptic";};
    if (y==103) {handle1 = "curious";};
    if (y==104) {handle1 = "cuttlefish";};
    if (y==105) {handle1 = "cynical";};
    return handle1;
}

string gethandle1D() {
    int y = rand() % (74) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "daedalus";};
    if (y==2) {handle1 = "daffy";};
    if (y==3) {handle1 = "daft";};
    if (y==4) {handle1 = "damascus";};
    if (y==5) {handle1 = "damiens";};
    if (y==6) {handle1 = "damnations";};
    if (y==7) {handle1 = "damnation";};
    if (y==8) {handle1 = "dangerous";};
    if (y==9) {handle1 = "dangerously";};
    if (y==10) {handle1 = "dapper";};
    if (y==11) {handle1 = "daredevil";};
    if (y==12) {handle1 = "dark";};
    if (y==13) {handle1 = "darkened";};
    if (y==14) {handle1 = "data";};
    if (y==15) {handle1 = "daydreaming";};
    if (y==16) {handle1 = "daylight";};
    if (y==17) {handle1 = "deadeye";};
    if (y==18) {handle1 = "deaf";};
    if (y==19) {handle1 = "debased";};
    if (y==20) {handle1 = "debonair";};
    if (y==21) {handle1 = "decaying";};
    if (y==22) {handle1 = "dedicated";};
    if (y==23) {handle1 = "defective";};
    if (y==24) {handle1 = "delay";};
    if (y==25) {handle1 = "deleterious";};
    if (y==26) {handle1 = "delightful";};
    if (y==27) {handle1 = "demonic";};
    if (y==28) {handle1 = "demon";};
    if (y==29) {handle1 = "demure";};
    if (y==30) {handle1 = "denied";};
    if (y==31) {handle1 = "deranged";};
    if (y==32) {handle1 = "descartes";};
    if (y==33) {handle1 = "desert";};
    if (y==34) {handle1 = "desk";};
    if (y==35) {handle1 = "destined";};
    if (y==36) {handle1 = "destiny";};
    if (y==37) {handle1 = "destitute";};
    if (y==38) {handle1 = "deviant";};
    if (y==39) {handle1 = "dielectric";};
    if (y==40) {handle1 = "different";};
    if (y==41) {handle1 = "diffident";};
    if (y==42) {handle1 = "digital";};
    if (y==43) {handle1 = "digladiate";};
    if (y==44) {handle1 = "diminutive";};
    if (y==45) {handle1 = "dionysus";};
    if (y==46) {handle1 = "director";};
    if (y==47) {handle1 = "directory";};
    if (y==48) {handle1 = "disc";};
    if (y==49) {handle1 = "dismay";};
    if (y==50) {handle1 = "dispassionate";};
    if (y==51) {handle1 = "disquisitive";};
    if (y==52) {handle1 = "diurnal";};
    if (y==53) {handle1 = "diverse";};
    if (y==54) {handle1 = "divvied";};
    if (y==55) {handle1 = "dockside";};
    if (y==56) {handle1 = "doctor";};
    if (y==57) {handle1 = "dodeca";};
    if (y==58) {handle1 = "dogmatic";};
    if (y==59) {handle1 = "doomsday";};
    if (y==60) {handle1 = "double";};
    if (y==61) {handle1 = "dragon";};
    if (y==62) {handle1 = "draconic";};
    if (y==63) {handle1 = "dream";};
    if (y==64) {handle1 = "dreaming";};
    if (y==65) {handle1 = "drunken";};
    if (y==66) {handle1 = "dual";};
    if (y==67) {handle1 = "dualtone";};
    if (y==68) {handle1 = "duckbilled";};
    if (y==69) {handle1 = "ductile";};
    if (y==70) {handle1 = "dusk";};
    if (y==71) {handle1 = "dusty";};
    if (y==72) {handle1 = "dutch";};
    if (y==73) {handle1 = "dynamic";};
    if (y==74) {handle1 = "dynamite";};
    return handle1;
}

string gethandle1E() {
    int y = rand() % (44) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "eccentric";};
    if (y==2) {handle1 = "eclectic";};
    if (y==3) {handle1 = "eclipse";};
    if (y==4) {handle1 = "ecliptic";};
    if (y==5) {handle1 = "ecstatic";};
    if (y==6) {handle1 = "ecto";};
    if (y==7) {handle1 = "edwards";};
    if (y==8) {handle1 = "eel";};
    if (y==9) {handle1 = "eightbit";};
    if (y==10) {handle1 = "eighth";};
    if (y==11) {handle1 = "elastic";};
    if (y==12) {handle1 = "elder";};
    if (y==13) {handle1 = "eldritch";};
    if (y==14) {handle1 = "elegant";};
    if (y==15) {handle1 = "elephantine";};
    if (y==16) {handle1 = "eleventh";};
    if (y==17) {handle1 = "elite";};
    if (y==18) {handle1 = "eloquent";};
    if (y==19) {handle1 = "elven";};
    if (y==20) {handle1 = "emerald";};
    if (y==21) {handle1 = "emergency";};
    if (y==22) {handle1 = "emergent";};
    if (y==23) {handle1 = "emotionless";};
    if (y==24) {handle1 = "endless";};
    if (y==25) {handle1 = "energetic";};
    if (y==26) {handle1 = "enraged";};
    if (y==27) {handle1 = "entrancing";};
    if (y==28) {handle1 = "enumerated";};
    if (y==29) {handle1 = "ephemeral";};
    if (y==30) {handle1 = "epicene";};
    if (y==31) {handle1 = "equestrian";};
    if (y==32) {handle1 = "erasmus";};
    if (y==33) {handle1 = "eratosthenes";};
    if (y==34) {handle1 = "eris";};
    if (y==35) {handle1 = "ermine";};
    if (y==36) {handle1 = "eternal";};
    if (y==37) {handle1 = "ethereal";};
    if (y==38) {handle1 = "eulers";};
    if (y==39) {handle1 = "evanescent";};
    if (y==40) {handle1 = "everlasting";};
    if (y==41) {handle1 = "exasperant";};
    if (y==42) {handle1 = "excellent";};
    if (y==43) {handle1 = "existential";};
    if (y==44) {handle1 = "extreme";};
    return handle1;
}

string gethandle1F() {
    int y = rand() % (39) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "factored";};
    if (y==2) {handle1 = "faithful";};
    if (y==3) {handle1 = "falsetto";};
    if (y==4) {handle1 = "feckless";};
    if (y==5) {handle1 = "fedora";};
    if (y==6) {handle1 = "felidae";};
    if (y==7) {handle1 = "felis";};
    if (y==8) {handle1 = "fell";};
    if (y==9) {handle1 = "felt";};
    if (y==10) {handle1 = "ferdinands";};
    if (y==11) {handle1 = "fetid";};
    if (y==12) {handle1 = "fibbonaccis";};
    if (y==13) {handle1 = "fifth";};
    if (y==14) {handle1 = "fired";};
    if (y==15) {handle1 = "first";};
    if (y==16) {handle1 = "fish";};
    if (y==17) {handle1 = "flacid";};
    if (y==18) {handle1 = "flamboyant";};
    if (y==19) {handle1 = "flaming";};
    if (y==20) {handle1 = "flotsam";};
    if (y==21) {handle1 = "forgetful";};
    if (y==22) {handle1 = "forgotten";};
    if (y==23) {handle1 = "fortuitous";};
    if (y==24) {handle1 = "fortunate";};
    if (y==25) {handle1 = "fourth";};
    if (y==26) {handle1 = "fractal";};
    if (y==27) {handle1 = "frantic";};
    if (y==28) {handle1 = "freedom";};
    if (y==29) {handle1 = "freelance";};
    if (y==30) {handle1 = "frequent";};
    if (y==31) {handle1 = "friendly";};
    if (y==32) {handle1 = "frightened";};
    if (y==33) {handle1 = "frozen";};
    if (y==34) {handle1 = "fruity";};
    if (y==35) {handle1 = "fuck";};
    if (y==36) {handle1 = "full";};
    if (y==37) {handle1 = "fullblown";};
    if (y==38) {handle1 = "furtive";};
    if (y==39) {handle1 = "future";};
    return handle1;
}

string gethandle1G() {
    int y = rand() % (55) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "gadget";};
    if (y==2) {handle1 = "galadriels";};
    if (y==3) {handle1 = "galaxy";};
    if (y==4) {handle1 = "gale";};
    if (y==5) {handle1 = "gall";};
    if (y==6) {handle1 = "gallant";};
    if (y==7) {handle1 = "gallavanting";};
    if (y==8) {handle1 = "gallows";};
    if (y==9) {handle1 = "gambling";};
    if (y==10) {handle1 = "gamma";};
    if (y==11) {handle1 = "gander";};
    if (y==12) {handle1 = "garden";};
    if (y==13) {handle1 = "gasper";};
    if (y==14) {handle1 = "gatekeeper";};
    if (y==15) {handle1 = "gaucherie";};
    if (y==16) {handle1 = "geeky";};
    if (y==17) {handle1 = "general";};
    if (y==18) {handle1 = "generous";};
    if (y==19) {handle1 = "genial";};
    if (y==20) {handle1 = "genuine";};
    if (y==21) {handle1 = "ghastly";};
    if (y==22) {handle1 = "ghost";};
    if (y==23) {handle1 = "ghostly";};
    if (y==24) {handle1 = "ghoul";};
    if (y==25) {handle1 = "gibbet";};
    if (y==26) {handle1 = "gilded";};
    if (y==27) {handle1 = "gingerbread";};
    if (y==28) {handle1 = "gladiate";};
    if (y==29) {handle1 = "glamorous";};
    if (y==30) {handle1 = "glittering";};
    if (y==31) {handle1 = "glowstick";};
    if (y==32) {handle1 = "gnarly";};
    if (y==33) {handle1 = "gnoseologic";};
    if (y==34) {handle1 = "god";};
    if (y==35) {handle1 = "godly";};
    if (y==36) {handle1 = "godmode";};
    if (y==37) {handle1 = "godsent";};
    if (y==38) {handle1 = "golden";};
    if (y==39) {handle1 = "golgothas";};
    if (y==40) {handle1 = "gothic";};
    if (y==41) {handle1 = "gradient";};
    if (y==42) {handle1 = "graphical";};
    if (y==43) {handle1 = "gravitys";};
    if (y==44) {handle1 = "greyscale";};
    if (y==45) {handle1 = "grey";};
    if (y==46) {handle1 = "grievous";};
    if (y==47) {handle1 = "grim";};
    if (y==48) {handle1 = "grimalkin";};
    if (y==49) {handle1 = "grimoire";};
    if (y==50) {handle1 = "guest";};
    if (y==51) {handle1 = "guided";};
    if (y==52) {handle1 = "guild";};
    if (y==53) {handle1 = "gummy";};
    if (y==54) {handle1 = "gun";};
    if (y==55) {handle1 = "gutsy";};
    return handle1;
}

string gethandle1H() {
    int y = rand() % (36) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "halcyon";};
    if (y==2) {handle1 = "handsome";};
    if (y==3) {handle1 = "handy";};
    if (y==4) {handle1 = "hardy";};
    if (y==5) {handle1 = "harmful";};
    if (y==6) {handle1 = "harmonica";};
    if (y==7) {handle1 = "hated";};
    if (y==8) {handle1 = "hatred";};
    if (y==9) {handle1 = "hazardous";};
    if (y==10) {handle1 = "healthy";};
    if (y==11) {handle1 = "heated";};
    if (y==12) {handle1 = "hefty";};
    if (y==13) {handle1 = "helio";};
    if (y==14) {handle1 = "helix";};
    if (y==15) {handle1 = "helpful";};
    if (y==16) {handle1 = "hemi";};
    if (y==17) {handle1 = "hemlock";};
    if (y==18) {handle1 = "heretical";};
    if (y==19) {handle1 = "hermetic";};
    if (y==20) {handle1 = "hetero";};
    if (y==21) {handle1 = "hex";};
    if (y==22) {handle1 = "hibiscus";};
    if (y==23) {handle1 = "highspeed";};
    if (y==24) {handle1 = "highway";};
    if (y==25) {handle1 = "hilarious";};
    if (y==26) {handle1 = "hippocrates";};
    if (y==27) {handle1 = "hopeless";};
    if (y==28) {handle1 = "horrible";};
    if (y==29) {handle1 = "hot";};
    if (y==30) {handle1 = "howling";};
    if (y==31) {handle1 = "humble";};
    if (y==32) {handle1 = "hungering";};
    if (y==33) {handle1 = "hybrid";};
    if (y==34) {handle1 = "hydro";};
    if (y==35) {handle1 = "hyperion";};
    if (y==36) {handle1 = "hysterical";};
    return handle1;
}

string gethandle1I() {
    int y = rand() % (44) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "ice";};
    if (y==2) {handle1 = "iconic";};
    if (y==3) {handle1 = "illegal";};
    if (y==4) {handle1 = "imminent";};
    if (y==5) {handle1 = "immortally";};
    if (y==6) {handle1 = "immortal";};
    if (y==7) {handle1 = "impassive";};
    if (y==8) {handle1 = "imperfect";};
    if (y==9) {handle1 = "impious";};
    if (y==10) {handle1 = "impish";};
    if (y==11) {handle1 = "inaccurate";};
    if (y==12) {handle1 = "incandescent";};
    if (y==13) {handle1 = "incapable";};
    if (y==14) {handle1 = "incipient";};
    if (y==15) {handle1 = "indigenous";};
    if (y==16) {handle1 = "influential";};
    if (y==17) {handle1 = "informative";};
    if (y==18) {handle1 = "inhospitable";};
    if (y==19) {handle1 = "inquiry";};
    if (y==20) {handle1 = "inquisitive";};
    if (y==21) {handle1 = "insanity";};
    if (y==22) {handle1 = "insatiable";};
    if (y==23) {handle1 = "insomniac";};
    if (y==24) {handle1 = "insouciant";};
    if (y==25) {handle1 = "instinctive";};
    if (y==26) {handle1 = "insufficient";};
    if (y==27) {handle1 = "intangible";};
    if (y==28) {handle1 = "intellectual";};
    if (y==29) {handle1 = "interloping";};
    if (y==30) {handle1 = "intolerant";};
    if (y==31) {handle1 = "intransigent";};
    if (y==32) {handle1 = "introverted";};
    if (y==33) {handle1 = "invisible";};
    if (y==34) {handle1 = "irascible";};
    if (y==35) {handle1 = "iron";};
    if (y==36) {handle1 = "irrational";};
    if (y==37) {handle1 = "irregular";};
    if (y==38) {handle1 = "irrelevant";};
    if (y==39) {handle1 = "irreverent";};
    if (y==40) {handle1 = "iscariots";};
    if (y==41) {handle1 = "ishmaels";};
    if (y==42) {handle1 = "isolated";};
    if (y==43) {handle1 = "isometric";};
    if (y==44) {handle1 = "isosceles";};
    return handle1;
}

string gethandle1J() {
    int y = rand() % (13) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "jackanape";};
    if (y==2) {handle1 = "jackrabbit";};
    if (y==3) {handle1 = "jailhouse";};
    if (y==4) {handle1 = "jasper";};
    if (y==5) {handle1 = "jealous";};
    if (y==6) {handle1 = "jest";};
    if (y==7) {handle1 = "jetsam";};
    if (y==8) {handle1 = "jewel";};
    if (y==9) {handle1 = "jive";};
    if (y==10) {handle1 = "jovial";};
    if (y==11) {handle1 = "jovian";};
    if (y==12) {handle1 = "judgement";};
    if (y==13) {handle1 = "judicial";};
    return handle1;
}

string gethandle1K() {
    int y = rand() % (14) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "keelhaul";};
    if (y==2) {handle1 = "kick";};
    if (y==3) {handle1 = "killer";};
    if (y==4) {handle1 = "king";};
    if (y==5) {handle1 = "kitten";};
    if (y==6) {handle1 = "kitty";};
    if (y==7) {handle1 = "klepto";};
    if (y==8) {handle1 = "knack";};
    if (y==9) {handle1 = "kneeling";};
    if (y==10) {handle1 = "knickknack";};
    if (y==11) {handle1 = "knife";};
    if (y==12) {handle1 = "knight";};
    if (y==13) {handle1 = "knotted";};
    if (y==14) {handle1 = "knowledgeable";};
    return handle1;
}

string gethandle1L() {
    int y = rand() % (38) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "lackadaisical";};
    if (y==2) {handle1 = "lady";};
    if (y==3) {handle1 = "lamppost";};
    if (y==4) {handle1 = "lancing";};
    if (y==5) {handle1 = "landed";};
    if (y==6) {handle1 = "last";};
    if (y==7) {handle1 = "lasting";};
    if (y==8) {handle1 = "laughable";};
    if (y==9) {handle1 = "law";};
    if (y==10) {handle1 = "lay";};
    if (y==11) {handle1 = "left";};
    if (y==12) {handle1 = "lemon";};
    if (y==13) {handle1 = "lethargic";};
    if (y==14) {handle1 = "level";};
    if (y==15) {handle1 = "ley";};
    if (y==16) {handle1 = "lay";};
    if (y==17) {handle1 = "liberal";};
    if (y==18) {handle1 = "life";};
    if (y==19) {handle1 = "lilting";};
    if (y==20) {handle1 = "limited";};
    if (y==21) {handle1 = "linguistic";};
    if (y==22) {handle1 = "listless";};
    if (y==23) {handle1 = "little";};
    if (y==24) {handle1 = "liveliest";};
    if (y==25) {handle1 = "living";};
    if (y==26) {handle1 = "lockup";};
    if (y==27) {handle1 = "lonely";};
    if (y==28) {handle1 = "lost";};
    if (y==29) {handle1 = "lovely";};
    if (y==30) {handle1 = "lucent";};
    if (y==31) {handle1 = "lucid";};
    if (y==32) {handle1 = "lucidly";};
    if (y==33) {handle1 = "lucky";};
    if (y==34) {handle1 = "lugubrious";};
    if (y==35) {handle1 = "luminescence";};
    if (y==36) {handle1 = "luminous";};
    if (y==37) {handle1 = "lupus";};
    if (y==38) {handle1 = "lustrous";};
    return handle1;
}

string gethandle1M() {
    int y = rand() % (59) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "madam";};
    if (y==2) {handle1 = "maelstrom";};
    if (y==3) {handle1 = "magic";};
    if (y==4) {handle1 = "magi";};
    if (y==5) {handle1 = "magical";};
    if (y==6) {handle1 = "magnanimous";};
    if (y==7) {handle1 = "mailin";};
    if (y==8) {handle1 = "maladroit";};
    if (y==9) {handle1 = "malignant";};
    if (y==10) {handle1 = "mangled";};
    if (y==11) {handle1 = "maniacal";};
    if (y==12) {handle1 = "manic";};
    if (y==13) {handle1 = "mankinds";};
    if (y==14) {handle1 = "martyrs";};
    if (y==15) {handle1 = "masked";};
    if (y==16) {handle1 = "master";};
    if (y==17) {handle1 = "matrix";};
    if (y==18) {handle1 = "masterful";};
    if (y==19) {handle1 = "mechanical";};
    if (y==20) {handle1 = "mega";};
    if (y==21) {handle1 = "megalomaniacal";};
    if (y==22) {handle1 = "mellow";};
    if (y==23) {handle1 = "memory";};
    if (y==24) {handle1 = "mended";};
    if (y==25) {handle1 = "meow";};
    if (y==26) {handle1 = "mental";};
    if (y==27) {handle1 = "metallic";};
    if (y==28) {handle1 = "methodical";};
    if (y==29) {handle1 = "meticulous";};
    if (y==30) {handle1 = "midnight";};
    if (y==31) {handle1 = "mighty";};
    if (y==32) {handle1 = "milky";};
    if (y==33) {handle1 = "miltonian";};
    if (y==34) {handle1 = "mindful";};
    if (y==35) {handle1 = "mini";};
    if (y==36) {handle1 = "mirror";};
    if (y==37) {handle1 = "mischievous";};
    if (y==38) {handle1 = "misfit";};
    if (y==39) {handle1 = "misguided";};
    if (y==40) {handle1 = "misleading";};
    if (y==41) {handle1 = "misled";};
    if (y==42) {handle1 = "misty";};
    if (y==43) {handle1 = "misunderstood";};
    if (y==44) {handle1 = "mixolydian";};
    if (y==45) {handle1 = "mobile";};
    if (y==46) {handle1 = "modern";};
    if (y==47) {handle1 = "mondegreen";};
    if (y==48) {handle1 = "monster";};
    if (y==49) {handle1 = "motherfucking";};
    if (y==50) {handle1 = "mouse";};
    if (y==51) {handle1 = "mr";};
    if (y==52) {handle1 = "mrs";};
    if (y==53) {handle1 = "multicolored";};
    if (y==54) {handle1 = "muramasas";};
    if (y==55) {handle1 = "musical";};
    if (y==56) {handle1 = "musicless";};
    if (y==57) {handle1 = "mycosynth";};
    if (y==58) {handle1 = "myopic";};
    if (y==59) {handle1 = "mysterious";};
    return handle1;
}

string gethandle1N() {
    int y = rand() % (18) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "nailfile";};
    if (y==2) {handle1 = "nasty";};
    if (y==3) {handle1 = "nefarious";};
    if (y==4) {handle1 = "neurotic";};
    if (y==5) {handle1 = "new";};
    if (y==6) {handle1 = "nickelplated";};
    if (y==7) {handle1 = "night";};
    if (y==8) {handle1 = "nightfall";};
    if (y==9) {handle1 = "nightmare";};
    if (y==10) {handle1 = "nightmarish";};
    if (y==11) {handle1 = "nihilistic";};
    if (y==12) {handle1 = "ninth";};
    if (y==13) {handle1 = "nitro";};
    if (y==14) {handle1 = "nitrous";};
    if (y==15) {handle1 = "nocturnal";};
    if (y==16) {handle1 = "non";};
    if (y==17) {handle1 = "nostalgic";};
    if (y==18) {handle1 = "notorious";};
    return handle1;
}

string gethandle1O() {
    int y = rand() % (21) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "oblivious";};
    if (y==2) {handle1 = "observing";};
    if (y==3) {handle1 = "octagon";};
    if (y==4) {handle1 = "octarine";};
    if (y==5) {handle1 = "octo";};
    if (y==6) {handle1 = "octuple";};
    if (y==7) {handle1 = "oddball";};
    if (y==8) {handle1 = "olden";};
    if (y==9) {handle1 = "olfactory";};
    if (y==10) {handle1 = "olivers";};
    if (y==11) {handle1 = "ominous";};
    if (y==12) {handle1 = "omnipotent";};
    if (y==13) {handle1 = "opportune";};
    if (y==14) {handle1 = "oppressive";};
    if (y==15) {handle1 = "orange";};
    if (y==16) {handle1 = "orderly";};
    if (y==17) {handle1 = "organized";};
    if (y==18) {handle1 = "ornery";};
    if (y==19) {handle1 = "ostentatious";};
    if (y==20) {handle1 = "outlandish";};
    if (y==21) {handle1 = "oxide";};
    return handle1;
}

string gethandle1P() {
    int y = rand() % (46) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "panda";};
    if (y==2) {handle1 = "pantomime";};
    if (y==3) {handle1 = "paragon";};
    if (y==4) {handle1 = "parallel";};
    if (y==5) {handle1 = "passionate";};
    if (y==6) {handle1 = "passive";};
    if (y==7) {handle1 = "pathological";};
    if (y==8) {handle1 = "patient";};
    if (y==9) {handle1 = "pattering";};
    if (y==10) {handle1 = "peerless";};
    if (y==11) {handle1 = "peppered";};
    if (y==12) {handle1 = "perma";};
    if (y==13) {handle1 = "persephones";};
    if (y==14) {handle1 = "perspicatious";};
    if (y==15) {handle1 = "petulant";};
    if (y==16) {handle1 = "photo";};
    if (y==17) {handle1 = "pickle";};
    if (y==18) {handle1 = "pitiful";};
    if (y==19) {handle1 = "planetary";};
    if (y==20) {handle1 = "plasma";};
    if (y==21) {handle1 = "pocket";};
    if (y==22) {handle1 = "poetic";};
    if (y==23) {handle1 = "polychrome";};
    if (y==24) {handle1 = "porcelaine";};
    if (y==25) {handle1 = "possessed";};
    if (y==26) {handle1 = "possessive";};
    if (y==27) {handle1 = "post";};
    if (y==28) {handle1 = "pre";};
    if (y==29) {handle1 = "precambrian";};
    if (y==30) {handle1 = "precarious";};
    if (y==31) {handle1 = "precise";};
    if (y==32) {handle1 = "prince";};
    if (y==33) {handle1 = "privateering";};
    if (y==34) {handle1 = "problem";};
    if (y==35) {handle1 = "problematic";};
    if (y==36) {handle1 = "professor";};
    if (y==37) {handle1 = "prophillic";};
    if (y==38) {handle1 = "prophetic";};
    if (y==39) {handle1 = "prophet";};
    if (y==40) {handle1 = "prophecy";};
    if (y==41) {handle1 = "pseudo";};
    if (y==42) {handle1 = "psyched";};
    if (y==43) {handle1 = "psychotic";};
    if (y==44) {handle1 = "pumpkin";};
    if (y==45) {handle1 = "pyrotechnic";};
    if (y==46) {handle1 = "pyromaniacal";};
    return handle1;
}

string gethandle1Q() {
    int y = rand() % (13) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "quantum";};
    if (y==2) {handle1 = "queasy";};
    if (y==3) {handle1 = "queens";};
    if (y==4) {handle1 = "query";};
    if (y==5) {handle1 = "quest";};
    if (y==6) {handle1 = "questionable";};
    if (y==7) {handle1 = "questionably";};
    if (y==8) {handle1 = "quibble";};
    if (y==9) {handle1 = "quick";};
    if (y==10) {handle1 = "quidditch";};
    if (y==11) {handle1 = "quirky";};
    if (y==12) {handle1 = "quisling";};
    if (y==13) {handle1 = "quinoa";};
    return handle1;
}

string gethandle1R() {
    int y = rand() % (40) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "rabid";};
    if (y==2) {handle1 = "racecar";};
    if (y==3) {handle1 = "radiant";};
    if (y==4) {handle1 = "rainbow";};
    if (y==5) {handle1 = "raked";};
    if (y==6) {handle1 = "rampaging";};
    if (y==7) {handle1 = "rampant";};
    if (y==8) {handle1 = "randomaccess";};
    if (y==9) {handle1 = "rank";};
    if (y==10) {handle1 = "ranting";};
    if (y==11) {handle1 = "raven";};
    if (y==12) {handle1 = "razor";};
    if (y==13) {handle1 = "razzle";};
    if (y==14) {handle1 = "reasoning";};
    if (y==15) {handle1 = "recalcitrant";};
    if (y==16) {handle1 = "redeyed";};
    if (y==17) {handle1 = "relentless";};
    if (y==18) {handle1 = "relic";};
    if (y==19) {handle1 = "religious";};
    if (y==20) {handle1 = "reliquary";};
    if (y==21) {handle1 = "reminiscing";};
    if (y==22) {handle1 = "reptilian";};
    if (y==23) {handle1 = "resolutely";};
    if (y==24) {handle1 = "resplendent";};
    if (y==25) {handle1 = "restful";};
    if (y==26) {handle1 = "restless";};
    if (y==27) {handle1 = "retro";};
    if (y==28) {handle1 = "revolver";};
    if (y==29) {handle1 = "rhapsody";};
    if (y==30) {handle1 = "right";};
    if (y==31) {handle1 = "righteous";};
    if (y==32) {handle1 = "ringed";};
    if (y==33) {handle1 = "ringing";};
    if (y==34) {handle1 = "ring";};
    if (y==35) {handle1 = "roaring";};
    if (y==36) {handle1 = "robotic";};
    if (y==37) {handle1 = "robust";};
    if (y==38) {handle1 = "rose";};
    if (y==39) {handle1 = "royal";};
    if (y==40) {handle1 = "ruling";};
    return handle1;
}

string gethandle1S() {
    int y = rand() % (87) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "sadistic";};
    if (y==2) {handle1 = "saffron";};
    if (y==3) {handle1 = "salacious";};
    if (y==4) {handle1 = "salarian";};
    if (y==5) {handle1 = "salty";};
    if (y==6) {handle1 = "sangfroid";};
    if (y==7) {handle1 = "sanguine";};
    if (y==8) {handle1 = "sapphire";};
    if (y==9) {handle1 = "sarcastic";};
    if (y==10) {handle1 = "sardonic";};
    if (y==11) {handle1 = "saturn";};
    if (y==12) {handle1 = "scales";};
    if (y==13) {handle1 = "schroedingers";};
    if (y==14) {handle1 = "scrying";};
    if (y==15) {handle1 = "second";};
    if (y==16) {handle1 = "seductive";};
    if (y==17) {handle1 = "selfish";};
    if (y==18) {handle1 = "sepulchral";};
    if (y==19) {handle1 = "sequel";};
    if (y==20) {handle1 = "sequestered";};
    if (y==21) {handle1 = "sequined";};
    if (y==22) {handle1 = "seraphic";};
    if (y==23) {handle1 = "serial";};
    if (y==24) {handle1 = "serious";};
    if (y==25) {handle1 = "sesquipodelian";};
    if (y==26) {handle1 = "seventh";};
    if (y==27) {handle1 = "severe";};
    if (y==28) {handle1 = "severed";};
    if (y==29) {handle1 = "shadow";};
    if (y==30) {handle1 = "shaman";};
    if (y==31) {handle1 = "shark";};
    if (y==32) {handle1 = "sherlocks";};
    if (y==33) {handle1 = "shining";};
    if (y==34) {handle1 = "shockwave";};
    if (y==35) {handle1 = "shotgun";};
    if (y==36) {handle1 = "sick";};
    if (y==37) {handle1 = "sightless";};
    if (y==38) {handle1 = "silence";};
    if (y==39) {handle1 = "silenced";};
    if (y==40) {handle1 = "silent";};
    if (y==41) {handle1 = "silicate";};
    if (y==42) {handle1 = "silk";};
    if (y==43) {handle1 = "sinister";};
    if (y==44) {handle1 = "sixth";};
    if (y==45) {handle1 = "sketchy";};
    if (y==46) {handle1 = "skull";};
    if (y==47) {handle1 = "sleepless";};
    if (y==48) {handle1 = "sleepy";};
    if (y==49) {handle1 = "slippery";};
    if (y==50) {handle1 = "smiling";};
    if (y==51) {handle1 = "sneaky";};
    if (y==52) {handle1 = "solar";};
    if (y==53) {handle1 = "somber";};
    if (y==54) {handle1 = "soulless";};
    if (y==55) {handle1 = "sovereign";};
    if (y==56) {handle1 = "space";};
    if (y==57) {handle1 = "spatula";};
    if (y==58) {handle1 = "spectral";};
    if (y==59) {handle1 = "spicebush";};
    if (y==60) {handle1 = "spider";};
    if (y==61) {handle1 = "spire";};
    if (y==62) {handle1 = "splenetic";};
    if (y==63) {handle1 = "split";};
    if (y==64) {handle1 = "spoiler";};
    if (y==65) {handle1 = "spotted";};
    if (y==66) {handle1 = "springtime";};
    if (y==67) {handle1 = "squeamish";};
    if (y==68) {handle1 = "stagnant";};
    if (y==69) {handle1 = "star";};
    if (y==70) {handle1 = "stealthy";};
    if (y==71) {handle1 = "stepping";};
    if (y==72) {handle1 = "storytelling";};
    if (y==73) {handle1 = "stray";};
    if (y==74) {handle1 = "stride";};
    if (y==75) {handle1 = "string";};
    if (y==76) {handle1 = "striped";};
    if (y==77) {handle1 = "subliminal";};
    if (y==78) {handle1 = "subversive";};
    if (y==79) {handle1 = "subzero";};
    if (y==80) {handle1 = "superficial";};
    if (y==81) {handle1 = "surreal";};
    if (y==82) {handle1 = "suspended";};
    if (y==83) {handle1 = "suspicious";};
    if (y==84) {handle1 = "sweet";};
    if (y==85) {handle1 = "systematic";};
    if (y==86) {handle1 = "system";};
    if (y==87) {handle1 = "systolic";};
    return handle1;
}

string gethandle1T() {
    int y = rand() % (68) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "tableturning";};
    if (y==2) {handle1 = "taciturn";};
    if (y==3) {handle1 = "tactic";};
    if (y==4) {handle1 = "tainted";};
    if (y==5) {handle1 = "talented";};
    if (y==6) {handle1 = "tangible";};
    if (y==7) {handle1 = "teasing";};
    if (y==8) {handle1 = "teatime";};
    if (y==9) {handle1 = "techno";};
    if (y==10) {handle1 = "technical";};
    if (y==11) {handle1 = "technicolor";};
    if (y==12) {handle1 = "technological";};
    if (y==13) {handle1 = "telepathic";};
    if (y==14) {handle1 = "tempered";};
    if (y==15) {handle1 = "temporal";};
    if (y==16) {handle1 = "tenacious";};
    if (y==17) {handle1 = "tenebrous";};
    if (y==18) {handle1 = "tentacle";};
    if (y==19) {handle1 = "tenth";};
    if (y==20) {handle1 = "terminally";};
    if (y==21) {handle1 = "test";};
    if (y==22) {handle1 = "teutonic";};
    if (y==23) {handle1 = "textbook";};
    if (y==24) {handle1 = "thalio";};
    if (y==25) {handle1 = "the";};
    if (y==26) {handle1 = "theatric";};
    if (y==27) {handle1 = "therapeutic";};
    if (y==28) {handle1 = "thereoid";};
    if (y==29) {handle1 = "thespian";};
    if (y==30) {handle1 = "third";};
    if (y==31) {handle1 = "thirsty";};
    if (y==32) {handle1 = "thralled";};
    if (y==33) {handle1 = "thread";};
    if (y==34) {handle1 = "threat";};
    if (y==35) {handle1 = "tidewater";};
    if (y==36) {handle1 = "timaeus";};
    if (y==37) {handle1 = "timely";};
    if (y==38) {handle1 = "timorous";};
    if (y==39) {handle1 = "tipsy";};
    if (y==40) {handle1 = "tireless";};
    if (y==41) {handle1 = "titanium";};
    if (y==42) {handle1 = "toasted";};
    if (y==43) {handle1 = "tolerant";};
    if (y==44) {handle1 = "torpid";};
    if (y==45) {handle1 = "toxic";};
    if (y==46) {handle1 = "track";};
    if (y==47) {handle1 = "tranquil";};
    if (y==48) {handle1 = "transient";};
    if (y==49) {handle1 = "transparent";};
    if (y==50) {handle1 = "tremendous";};
    if (y==51) {handle1 = "triskelion";};
    if (y==52) {handle1 = "trivial";};
    if (y==53) {handle1 = "trooper";};
    if (y==54) {handle1 = "troublesome";};
    if (y==55) {handle1 = "true";};
    if (y==56) {handle1 = "truly";};
    if (y==57) {handle1 = "trusty";};
    if (y==58) {handle1 = "trying";};
    if (y==59) {handle1 = "tumbling";};
    if (y==60) {handle1 = "tuneful";};
    if (y==61) {handle1 = "turbid";};
    if (y==62) {handle1 = "turntable";};
    if (y==63) {handle1 = "turntech";};
    if (y==64) {handle1 = "twelfth";};
    if (y==65) {handle1 = "twin";};
    if (y==66) {handle1 = "twisted";};
    if (y==67) {handle1 = "twofold";};
    if (y==68) {handle1 = "tyrannical";};
    return handle1;
}

string gethandle1U() {
    int y = rand() % (26) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "udder";};
    if (y==2) {handle1 = "ulterior";};
    if (y==3) {handle1 = "ultimate";};
    if (y==4) {handle1 = "umbrella";};
    if (y==5) {handle1 = "uncanny";};
    if (y==6) {handle1 = "uncertain";};
    if (y==7) {handle1 = "undaunted";};
    if (y==8) {handle1 = "undefined";};
    if (y==9) {handle1 = "undistinguished";};
    if (y==10) {handle1 = "undone";};
    if (y==11) {handle1 = "undying";};
    if (y==12) {handle1 = "ungodly";};
    if (y==13) {handle1 = "union";};
    if (y==14) {handle1 = "unit";};
    if (y==15) {handle1 = "united";};
    if (y==16) {handle1 = "universally";};
    if (y==17) {handle1 = "unnoticed";};
    if (y==18) {handle1 = "unstable";};
    if (y==19) {handle1 = "unsuccessful";};
    if (y==20) {handle1 = "untested";};
    if (y==21) {handle1 = "untreated";};
    if (y==22) {handle1 = "unusual";};
    if (y==23) {handle1 = "unyielding";};
    if (y==24) {handle1 = "upper";};
    if (y==25) {handle1 = "utmost";};
    if (y==26) {handle1 = "utter";};
    return handle1;
}

string gethandle1V() {
    int y = rand() % (24) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "valence";};
    if (y==2) {handle1 = "valiant";};
    if (y==3) {handle1 = "vampiric";};
    if (y==4) {handle1 = "vandal";};
    if (y==5) {handle1 = "vapid";};
    if (y==6) {handle1 = "vernacular";};
    if (y==7) {handle1 = "vegas";};
    if (y==8) {handle1 = "venemous";};
    if (y==9) {handle1 = "vengeful";};
    if (y==10) {handle1 = "versimilar";};
    if (y==11) {handle1 = "vested";};
    if (y==12) {handle1 = "vicious";};
    if (y==13) {handle1 = "vile";};
    if (y==14) {handle1 = "vilified";};
    if (y==15) {handle1 = "viperous";};
    if (y==16) {handle1 = "virtual";};
    if (y==17) {handle1 = "vivacious";};
    if (y==18) {handle1 = "vivid";};
    if (y==19) {handle1 = "vodka";};
    if (y==20) {handle1 = "volcanic";};
    if (y==21) {handle1 = "voluble";};
    if (y==22) {handle1 = "voluminous";};
    if (y==23) {handle1 = "volumptuous";};
    if (y==24) {handle1 = "vortex";};
    return handle1;
}

string gethandle1W() {
    int y = rand() % (16) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "waffle";};
    if (y==2) {handle1 = "walking";};
    if (y==3) {handle1 = "wandering";};
    if (y==4) {handle1 = "waste";};
    if (y==5) {handle1 = "wasteful";};
    if (y==6) {handle1 = "watery";};
    if (y==7) {handle1 = "wealthy";};
    if (y==8) {handle1 = "weaponized";};
    if (y==9) {handle1 = "wearied";};
    if (y==10) {handle1 = "western";};
    if (y==11) {handle1 = "whimsical";};
    if (y==12) {handle1 = "whispy";};
    if (y==13) {handle1 = "wise";};
    if (y==14) {handle1 = "wistful";};
    if (y==15) {handle1 = "withholding";};
    if (y==16) {handle1 = "wonderful";};
    return handle1;
}

string gethandle1X() {
    int y = rand() % (21) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "xaviers";};
    if (y==2) {handle1 = "xenial";};
    if (y==3) {handle1 = "xeno";};
    if (y==4) {handle1 = "xenogenetic";};
    if (y==5) {handle1 = "xenon";};
    if (y==6) {handle1 = "xenophyllic";};
    if (y==7) {handle1 = "xenophobic";};
    if (y==8) {handle1 = "xeophyte";};
    if (y==9) {handle1 = "xeranthemum";};
    if (y==10) {handle1 = "xeric";};
    if (y==11) {handle1 = "xerox";};
    if (y==12) {handle1 = "xerxes";};
    if (y==13) {handle1 = "xinjiang";};
    if (y==14) {handle1 = "xiphoid";};
    if (y==15) {handle1 = "xlinked";};
    if (y==16) {handle1 = "xray";};
    if (y==17) {handle1 = "xtreme";};
    if (y==18) {handle1 = "xyelidae";};
    if (y==19) {handle1 = "xylene";};
    if (y==20) {handle1 = "xylogen";};
    if (y==21) {handle1 = "xzylic";};
    return handle1;
}

string gethandle1Y() {
    int y = rand() % (18) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "yacht";};
    if (y==2) {handle1 = "yam";};
    if (y==3) {handle1 = "yard";};
    if (y==4) {handle1 = "yarn";};
    if (y==5) {handle1 = "ycleped";};
    if (y==6) {handle1 = "yearning";};
    if (y==7) {handle1 = "yeast";};
    if (y==8) {handle1 = "yeats";};
    if (y==9) {handle1 = "yellowbellied";};
    if (y==10) {handle1 = "yeoman";};
    if (y==11) {handle1 = "yesterdays";};
    if (y==12) {handle1 = "yew";};
    if (y==13) {handle1 = "yggdrasils";};
    if (y==14) {handle1 = "yinyang";};
    if (y==15) {handle1 = "yogi";};
    if (y==16) {handle1 = "yolk";};
    if (y==17) {handle1 = "younger";};
    if (y==18) {handle1 = "your";};
    return handle1;
}

string gethandle1Z() {
    int y = rand() % (21) + 1;
    string handle1 = "";
    if (y==1) {handle1 = "zagreus";};
    if (y==2) {handle1 = "zany";};
    if (y==3) {handle1 = "zapotec";};
    if (y==4) {handle1 = "zealous";};
    if (y==5) {handle1 = "zebra";};
    if (y==6) {handle1 = "zeitgeist";};
    if (y==7) {handle1 = "zen";};
    if (y==8) {handle1 = "zeolitic";};
    if (y==9) {handle1 = "zoo";};
    if (y==10) {handle1 = "zero";};
    if (y==11) {handle1 = "zeroth";};
    if (y==12) {handle1 = "zesty";};
    if (y==13) {handle1 = "zeta";};
    if (y==14) {handle1 = "zeugma";};
    if (y==15) {handle1 = "ziggurat";};
    if (y==16) {handle1 = "zillionth";};
    if (y==17) {handle1 = "zinc";};
    if (y==18) {handle1 = "zombie";};
    if (y==19) {handle1 = "zootic";};
    if (y==20) {handle1 = "zuccini";};
    if (y==21) {handle1 = "zygote";};
    return handle1;
}
